source 'git@git.xiaojukeji.com:ios/cocoapods-specs.git'
source 'git@git.xiaojukeji.com:one-ios/Specs.git'
platform :ios, '7.0'

# We don't use Swift internally. Disable this option.
#use_frameworks!

# Use local pod code if available.
def local_pod(name, *args)
  path = File.expand_path name, '../..'

  if File.exist? path
    pod name, :path => path
  else
    pod name, *args
  end
end

# Add global dependencies here.

target 'CPInfiniteBanner_Example', :exclusive => true do
  # If CPInfiniteBanner depends on any private pod, remember to use `local_pod`
  # to refer it explicitly.
  # CocoaPods cannot distinguish public and private pod from podspec right now,
  # it's required to do so in Podfile.
  #
  # Sample:
  #   local_pod "AnInternalPod", :git => "https://git.xiaojukeji.com/path/to/pod.git", :tag => "stable-tag"

  # Add Example specific dependencies here...

  pod "CPInfiniteBanner", :path => "../"
end

target 'CPInfiniteBanner_Tests', :exclusive => true do
  # Add Tests specific dependencies here...

  pod "CPInfiniteBanner", :path => "../"

  pod 'Kiwi'
end
